version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${postgres_user}
      POSTGRES_PASSWORD: ${auth_password}
      POSTGRES_DB: ${user_db}
    networks:
      - pgnetwork
    restart: always

networks:
  pgnetwork:
    driver: bridge
