name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-cicd.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-cicd.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test -- --watchAll=false

      - name: Build
        run: npm run build

      - name: Build Docker image
        run: docker build -t cartly-frontend:latest .

      # Optional: Push to Docker Hub or GitHub Container Registry
      # - name: Log in to DockerHub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #
      # - name: Push Docker image
      #   run: docker tag cartly-frontend:latest yourdockerhubuser/cartly-frontend:latest
      #   run: docker push yourdockerhubuser/cartly-frontend:latest

  # Optional: Deploy job (if you have a remote server)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   steps:
  #     - name: Deploy to server
  #       run: |
  #         ssh user@your-server 'cd /path/to/project && docker-compose pull && docker-compose up -d' 